spring.application.name=catalogo-service

# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_catalogo?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8082

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

springdoc.api-docs.resolve-schema-properties=true

# Security
application.security.jwt.secret-key=${JWT_SECRET_KEY:7b3d92a1f5e4c2b8a0d9e8f7a6b5c4d3210f9876543210fedcba9876543210ab}
application.security.jwt.expiration=3600000